name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  quality:
    name: Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: Install uv
        run: pipx install uv
      - name: Sync dependencies
        run: uv sync --dev --locked --no-build --no-install-project
      - name: Ruff lint
        run: uv run --locked --no-sync ruff check .
      - name: Ruff format
        run: uv run --locked --no-sync ruff format --check .
      - name: Pytest
        run: uv run --locked --no-sync pytest
      - name: Pre-commit
        run: uv run --locked --no-sync pre-commit run --all-files
